services:

    #
    # Related Purchasables Provider Adapters
    #
    elcodi.related_purchasables_provider.same_category:
        class: Elcodi\Component\Article\Adapter\SimilarPurchasablesProvider\SameCategoryRelatedPurchasableProvider
        arguments:
            - '@elcodi.repository.purchasable'
            - '@elcodi.repository.article'
            
    #
    # Printable Position Adapter
    #
    elcodi.article.adapter.printable_position:
        class: Elcodi\Component\Article\Adapter\PrintablePositionAdapter
        
    #
    # Printable Variant Size Adapter
    #
    elcodi.article.adapter.printable_size:
        class: Elcodi\Component\Article\Adapter\PrintableSizeAdapter
   
        