services:

    #
    # Name resolvers
    #
    elcodi.name_resolver.article:
        class: Elcodi\Component\Article\NameResolver\ArticleNameResolver
        tags:
            - { name: elcodi.purchasable_name_resolver }

    elcodi.name_resolver.article_variant:
        class: Elcodi\Component\Article\NameResolver\VariantNameResolver
        tags:
            - { name: elcodi.purchasable_name_resolver }

    elcodi.name_resolver.purchasable:
        class: Elcodi\Component\Article\NameResolver\PurchasableNameResolver
