services:

    #
    # Object Managers
    #
    elcodi.object_manager.purchasable:
        parent: elcodi.abstract_manager
        arguments:
            - %elcodi.entity.purchasable.class%

    elcodi.object_manager.article:
        parent: elcodi.abstract_manager
        arguments:
            - %elcodi.entity.article.class%
   
    elcodi.object_manager.category:
        parent: elcodi.abstract_manager
        arguments:
            - %elcodi.entity.category.class%

