services:

    #
    # Repositories
    #

    #
    # Repository for abstract purchasable
    #
    elcodi.repository.purchasable:
        parent: elcodi.abstract_repository
        arguments:
            - %elcodi.entity.purchasable.class%

    #
    # Repository for entity article
    #
    elcodi.repository.article:
        parent: elcodi.abstract_repository
        arguments:
            - %elcodi.entity.article.class%    

    
