services:

    #
    # Validators
    #
    elcodi.stock_validator.article:
        class: Elcodi\Component\Article\StockValidator\ArticleStockValidator
        tags:
            - { name: elcodi.purchasable_stock_validator }

    elcodi.stock_validator.purchasable:
        class: Elcodi\Component\Article\StockValidator\PurchasableStockValidator
