services:

    #
    # Services
    #
    elcodi.provider.category_tree:
        class: Elcodi\Component\Article\Services\CategoryTree
        arguments:
            - '@elcodi.repository.category'

    elcodi.service.category_integrity_fixer:
        class: Elcodi\Component\Article\Services\CategoryIntegrityFixer

    elcodi.resolver.article_options:
        class: Elcodi\Component\Article\Services\ArticleOptionsResolver
