elcodi_entity_translator:
    auto_translate: true
    language:
        master_locale: %locale%
        fallback: true
    configuration:
        Elcodi\Component\Article\Entity\Interfaces\PurchasableInterface:
            alias: purchasable
            fields:
                name: ~
                slug: ~
                metaTitle: ~
                metaDescription: ~
                metaKeywords: ~
        Elcodi\Bundle\ProductBundle\Entity\Product:
            alias: product
            fields:
                name: ~
                slug: ~
                description: ~
        Elcodi\Bundle\CategoryBundle\Entity\Interfaces\CategoryInterface:
            alias: category
            fields:
                name: ~
                slug: ~
                metaTitle: ~
                metaDescription: ~
                metaKeywords: ~    
        Elcodi\Bundle\ProductBundle\Entity\Interfaces\ProductManufacturerInterface:
            alias: manufacturer
            fields:
                name: ~
                slug: ~
                description: ~
                metaTitle: ~
                metaDescription: ~
                metaKeywords: ~
        Elcodi\Component\Page\Entity\Interfaces\PageInterface:
            alias: page
            fields:
                title: ~
                content: ~
                path: ~
                metaTitle: ~
                metaDescription: ~
                metaKeywords: ~
